spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: item-service
  # data-base configuration
  datasource:
    url: jdbc:mysql://localhost:3306/itemdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pratap
    password: pratap
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate.ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          generate_statistics: true
server:
  port: 9091
  servlet:
    context-path: /item-service
  # Bean validation
  error:
    include-message: always
    include-binding-errors: always
# coupon-service url
#coupon-service:
#  url: http://localhost:9092/coupon-service/coupons/

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka